name: yt_converter
description: "Youtube converter made by Vustron."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.3.7
  path_provider: ^2.1.1
  permission_handler: ^10.4.5
  page_transition: ^2.1.0
  flutter_animate: ^4.3.0
  animated_text_kit: ^4.2.2
  flutter_spinkit: ^5.2.1
  flutter_launcher_icons: ^0.13.1
  path: ^1.8.3
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  shared_preferences: ^2.3.1
  google_nav_bar: ^5.0.6
  icons_plus: ^5.0.0
  searchfield: ^1.0.9
  url_launcher: ^6.3.0
  youtube_explode_dart: ^1.10.4
  http: ^0.13.6
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_native_splash: ^2.3.8
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
  
# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icons/icon.png"
  adaptive_icon_background: "#ffffff"

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/icon.png"
